// ⚠️ The `value` keys here are duplicated in backend/config/profile_options.php.
// Backend is the source of truth. Keep both lists of keys in sync.
// Only value keys are duplicated; display labels live in messages/en.json and messages/ja.json.

export interface SelectOption {
  value: string;
  label: string; // English fallback label
}

export const NATIONALITY_OPTIONS: readonly SelectOption[] = [
  { value: "vietnamese", label: "Vietnamese" },
  { value: "chinese", label: "Chinese" },
  { value: "filipino", label: "Filipino" },
  { value: "nepali", label: "Nepali" },
  { value: "indonesian", label: "Indonesian" },
  { value: "myanmar", label: "Myanmar" },
  { value: "korean", label: "Korean" },
  { value: "thai", label: "Thai" },
  { value: "cambodian", label: "Cambodian" },
  { value: "brazilian", label: "Brazilian" },
  { value: "indian", label: "Indian" },
  { value: "bangladeshi", label: "Bangladeshi" },
  { value: "sri_lankan", label: "Sri Lankan" },
  { value: "mongolian", label: "Mongolian" },
  { value: "american", label: "American" },
  { value: "british", label: "British" },
  { value: "other", label: "Other" },
] as const;

export const LANGUAGE_OPTIONS: readonly SelectOption[] = [
  { value: "english", label: "English" },
  { value: "japanese", label: "Japanese" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "chinese", label: "Chinese" },
  { value: "tagalog", label: "Tagalog" },
  { value: "nepali", label: "Nepali" },
  { value: "indonesian", label: "Indonesian" },
  { value: "burmese", label: "Burmese" },
  { value: "korean", label: "Korean" },
  { value: "thai", label: "Thai" },
  { value: "khmer", label: "Khmer" },
  { value: "portuguese", label: "Portuguese" },
  { value: "hindi", label: "Hindi" },
  { value: "bengali", label: "Bengali" },
  { value: "other", label: "Other" },
] as const;

export const OCCUPATION_OPTIONS: readonly SelectOption[] = [
  { value: "caregiver", label: "Caregiver / Nursing Care" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "construction", label: "Construction" },
  { value: "agriculture", label: "Agriculture" },
  { value: "food_service", label: "Food Service" },
  { value: "hospitality", label: "Hospitality" },
  { value: "it_engineering", label: "IT / Engineering" },
  { value: "logistics", label: "Logistics" },
  { value: "retail", label: "Retail" },
  { value: "cleaning", label: "Cleaning" },
  { value: "education", label: "Education / Language Teaching" },
  { value: "healthcare", label: "Healthcare" },
  { value: "office", label: "Office / Administration" },
  { value: "student", label: "Student" },
  { value: "other", label: "Other" },
] as const;

export const PREFECTURE_OPTIONS: readonly SelectOption[] = [
  { value: "hokkaido", label: "Hokkaido" },
  { value: "aomori", label: "Aomori" },
  { value: "iwate", label: "Iwate" },
  { value: "miyagi", label: "Miyagi" },
  { value: "akita", label: "Akita" },
  { value: "yamagata", label: "Yamagata" },
  { value: "fukushima", label: "Fukushima" },
  { value: "ibaraki", label: "Ibaraki" },
  { value: "tochigi", label: "Tochigi" },
  { value: "gunma", label: "Gunma" },
  { value: "saitama", label: "Saitama" },
  { value: "chiba", label: "Chiba" },
  { value: "tokyo", label: "Tokyo" },
  { value: "kanagawa", label: "Kanagawa" },
  { value: "niigata", label: "Niigata" },
  { value: "toyama", label: "Toyama" },
  { value: "ishikawa", label: "Ishikawa" },
  { value: "fukui", label: "Fukui" },
  { value: "yamanashi", label: "Yamanashi" },
  { value: "nagano", label: "Nagano" },
  { value: "gifu", label: "Gifu" },
  { value: "shizuoka", label: "Shizuoka" },
  { value: "aichi", label: "Aichi" },
  { value: "mie", label: "Mie" },
  { value: "shiga", label: "Shiga" },
  { value: "kyoto", label: "Kyoto" },
  { value: "osaka", label: "Osaka" },
  { value: "hyogo", label: "Hyogo" },
  { value: "nara", label: "Nara" },
  { value: "wakayama", label: "Wakayama" },
  { value: "tottori", label: "Tottori" },
  { value: "shimane", label: "Shimane" },
  { value: "okayama", label: "Okayama" },
  { value: "hiroshima", label: "Hiroshima" },
  { value: "yamaguchi", label: "Yamaguchi" },
  { value: "tokushima", label: "Tokushima" },
  { value: "kagawa", label: "Kagawa" },
  { value: "ehime", label: "Ehime" },
  { value: "kochi", label: "Kochi" },
  { value: "fukuoka", label: "Fukuoka" },
  { value: "saga", label: "Saga" },
  { value: "nagasaki", label: "Nagasaki" },
  { value: "kumamoto", label: "Kumamoto" },
  { value: "oita", label: "Oita" },
  { value: "miyazaki", label: "Miyazaki" },
  { value: "kagoshima", label: "Kagoshima" },
  { value: "okinawa", label: "Okinawa" },
] as const;
